% Create the window
window = figure('position',[0 0 700 500],...
                'unit','pixels',...
                'name','Sudoko Solver',...
                'visible','on');
movegui(window,'northwest')

% Create the grid
CornerX = 25;
CornerY = 410;
dx = 35;
dy = 35;
for ii = 1:9
    for jj = 1:9
        xPos = CornerX + (jj-1)*dx;
        yPos = CornerY - (ii-1)*dy; 
        if (ii <= 3 && jj <= 3) || (ii >= 7 && jj <=3) || (ii >= 7 && jj >=7) || ((ii > 3 && ii < 7) && (jj > 3 && jj < 7)) || (jj >= 7 && ii <=3)
            sudokugui.X(ii,jj) = uicontrol('unit','pixels',...
                                       'background','w',...
                                       'Style','edit',...
                                       'visible','on',...
                                       'position',[xPos,yPos,dx dy],...
                                       'fontsize',14',...
                                       'fontweight','normal',...
                                       'enable','on',...
                                       'KeyPressFcn',{@sEntry,window,ii,jj});
        else
            sudokugui.X(ii,jj) = uicontrol('unit','pixels',...
                                       'background','#9ea5b0',...
                                       'Style','edit',...
                                       'visible','on',...
                                       'position',[xPos,yPos,dx dy],...
                                       'fontsize',14',...
                                       'fontweight','normal',...
                                       'enable','on',...
                                       'KeyPressFcn',{@sEntry,window,ii,jj});
        end
    end
end

% Add control to solve the sudoku
sudokugui.sove = 